### ISSUE TITLE
peeksoft.co, www.peeksoft.co

### ISSUE THREAD

**Issue by mikezliu** [ftpmorph/ftpihole#1]
Could the following two domains be whitelisted?
https://peeksoft.co
https://www.peeksoft.co

The domain is for a portfolio management application. Most of the app functionalities are broken, such as sync'ing data across devices, fetching news, financial data, in general using the app is broken, etc. The app only uses google for advertising. May I ask if the two domains were pulled from an upstream list?

**Comment by ftpmorph** [comment]
Thank you for bringing this to my attention. Looking into it, this is a bit of a complex one, as this domain does also serve up ads rather than only using Google. Peeksoft.co's homepage says they offer contextual advertising. A stock portfolio app I used on Android was also calling to this domain in order to display ads which disappeared when it was blocked.

At the same time you are correct the domain is also used by the portfolio management app so it is breaking functionality.

I will remove these domains for now until I can look into it further. Perhaps there is advertising subdomain I could block which will not harm the functioning of their portfolio management app.

I will update the list to comment out these domains right now so update your lists and the block should be removed assuming only my list is blocking it.

Apologies for the inconvenience.

**Comment by ftpmorph** [comment]
Can confirm the latest version of the smartphone blocklist is no longer blocking these domains. They have been commented out until I can work out if their ads can be blocked without damaging the functionality of their portfolio app e.g. by targeting an advertising subdomain.

If not, I will leave this domain unblocked as it's not malicious and I'd rather a few ads get through than to stop legitimate apps from functioning.
